apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: witcherapp
  ports:
    - protocol: TCP
      port: 4321
      targetPort: 4321
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: witcherapp
  replicas: 2
  template:
    metadata:
      labels:
        app: witcherapp
    spec:
      containers:
        - name: server
          imagePullPolicy: Always
          image: iuwitcher2020/dockerized_session_management_v1:latest
          ports:
            - containerPort: 4321