apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    name: server
    app: witcherapp

spec:
  selector:
    name: server
  type: LoadBalancer
  ports:
   - name: http
     port: 4321
     targetPort: 4321
     nodePort: 32171
     protocol: TCP