cd data-retrieval/
bash installation.sh
cd ..
cd post-processing/
bash installation.sh
cd ..
cd api-gateway/
bash installation.sh
cd ..
cd model-execution/
bash installation.sh
cd ..
cd session-management/
bash installation.sh
cd ..
cd ui/
bash installation.sh
cd ..
cd user-management/
bash installation.sh
cd ..
