apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5000
    port: 5000
    nodePort: 30000
 selector:
  app: api_gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    version: v1
spec:
  selector:
    matchLabels:
      app: api_gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api_gateway
    spec:
      containers:
      - name: api-gateway
        imagePullPolicy: Always
        image: iuwitcher2020/dockerized_api_gateway_v1:latest
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-v2
  labels:
    version: v2
spec:
  selector:
    matchLabels:
      app: api_gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api_gateway
    spec:
      containers:
      - name: api-gateway
        imagePullPolicy: Always
        image: iuwitcher2020/dockerized_api_gateway_v2:latest
        ports:
        - containerPort: 5000
