apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: mongo
    app: witcherapp

spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017

        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db

      # volumes:
      #     - name: mongo-storage
      #       hostPath:
      #         path: /data/db