apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-v2
  labels:
    version: v2
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        imagePullPolicy: Always
        image: iuwitcher2020/docker-ui-v2:latest
        ports:
        - containerPort: 3000
